#!/bin/bash

cat $HOME/.xmonad/xmonad.hs | awk '/START_KEYS/,/END_KEYS/' \
  | grep -e ', ("' -e '\[ ("' -e 'KB_GROUP' | grep -v '\-\- , ("' \
  | sed -e 's/^[ \t]*//' -e 's/, (//' -e 's/\[ (//' -e 's/)//' \
    -e 's/-- KB_GROUP /\n/' -e 's/, / : /' \
  | yad --text-info --geometry=1200x800 --fore=#8be9fd
