#!/usr/bin/env bash

rofi_dir="$HOME/.config/rofi"
rofi_command="rofi -dmenu -theme $rofi_dir/launchers/type-1/style-11.rasi"

options=()
for dir in "$rofi_dir"/launchers/*/; do
    options+=("$(basename "$dir")")
done

type=$(printf "%s\n" "${options[@]}" | $rofi_command)

[[ -n "$type" ]] || exit 1

styles=$(ls $rofi_dir/launchers/$type | grep rasi | sort | sed 's/.rasi//')
style=$(printf "%s\n" "${styles[@]}" | $rofi_command)

[[ -n "$style" ]] || exit 1

echo "$type" > "${rofi_dir}/.type"
echo "$style" > "${rofi_dir}/.style"

exit 0
