# Inserts a blank line between shell prompts
add_newline = false

format = """
[](bold blue) $username\
${custom.home_icon}${custom.dir_icon}\
$directory\
$git_branch\
$git_status\
$character\
"""

# Makes prompt a single line instead of two
[line_break]
disabled = true

[character]
success_symbol = "[](bold green)"
error_symbol = "[](bold red)"

[directory]
truncate_to_repo = false
style = "bold red"
format = ' [$path]($style)[$read_only]($read_only_style) '

[git_branch]
style = "bold cyan"
symbol = ""
format = '[$symbol $branch(:$remote_branch)]($style) '

[git_status]
style = "bold yellow"
format = '([$all_status$ahead_behind]($style) )'

[username]
show_always = true
style_user = "bold purple"
format = ' [$user]($style) '

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[cmd_duration]
min_time = 200
format = "took [$duration](bold yellow)"

[custom.home_icon]
symbol = ''
when = ''' test "$HOME" = "$PWD" '''
style = "bold black"
format = '[$symbol]($style) '

[custom.dir_icon]
symbol = ''
when = ''' test ! "$HOME" = "$PWD" '''
style = "bold cyan"
format = '[$symbol]($style) '
