#! /bin/sh

### AUTOSTART ###
lxpolkit &
sxhkd &
nm-applet &
dunst &
setxkbmap br &
xset s off -dpms &
playerctld daemon &
nitrogen --restore &
/usr/bin/emacs --daemon &
pulsemixer --set-volume 100 &
$HOME/.config/polybar/launch.sh --space &
picom --config ~/.config/picom/picom.conf -b &

[[ -n $(xrandr -q | grep -w DP-1) ]] && $HOME/.screenlayout/dual-monitor.sh &

### WORKSPACES ###
bspc monitor HDMI-0 -d 1 2 3 4 5 6
bspc monitor DP-1 -d 1 2 3 4 5 6

#### BSPWM configuration ####
#bspc config border_radius                8
bspc config border_width                  2
bspc config window_gap                    6
bspc config top_padding                   42 # Space
#bspc config top_padding                   28 # Powerline
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0
bspc config single_monocle                false
bspc config click_to_focus                true
bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config focus_by_distance             true
bspc config focus_follows_pointer         true
bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

#### BSPWM coloring ####
bspc config normal_border_color		      "#44475a"
bspc config active_border_color	        "#44475a"
#bspc config focused_border_color	      "#8d62ad" # Powerline
bspc config focused_border_color	      "#ff79c6" # Space
bspc config presel_feedback_color	      "#bd93f9"
bspc config urgent_border_color 	      "#ff5555"

#polybar hidden when fullscreen for vlc, youtube, mpv ...
xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_HDMI-0)
xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DP-1)

### Window rules ###
bspc rule -a Emacs state=tiled
bspc rule -a Yad state=floating
bspc rule -a Gimp state=floating
#bspc rule -a Steam state=floating
#bspc rule -a Lutris state=floating
bspc rule -a Volctl state=floating
bspc rule -a VirtualBox Manager state=floating
bspc rule -a feh state=floating
bspc rule -a simple-camera state=floating

# Switch-to-desktop rules #
bspc rule -a neovide follow=on
bspc rule -a LibreWolf follow=on
bspc rule -a Brave-browser follow=on
bspc rule -a Godot state=floating
bspc rule -a VirtualBox Machine follow=on
bspc rule -a Qalculate-gtk state=floating
