#!/usr/bin/env bash
#  ╔═╗╔═╗╔═╗╔═╗  ╦  ╔═╗╦ ╦╔╗╔╔═╗╦ ╦╔═╗╦═╗
#  ╠═╣╠═╝╠═╝╚═╗  ║  ╠═╣║ ║║║║║  ╠═╣║╣ ╠╦╝
#  ╩ ╩╩  ╩  ╚═╝  ╩═╝╩ ╩╚═╝╝╚╝╚═╝╩ ╩╚═╝╩╚═
#	Script to control apps launcher
#   Author: z0mbi3
#	url: https://github.com/gh0stzk

# From here you can control your favorite applications for all themes.

case "$1" in
  --menu)
    read -r TYPE < "$HOME/.config/rofi/.type"
    $HOME/.config/rofi/launchers/$TYPE/launcher.sh;;
    # rofi -show drun \
		 # -theme $HOME/.config/bspwm/rices/${RICETHEME}/launcher.rasi;;

  --scripts)
    rofi -show emoji -kb-custom-1 Ctrl+Shift+c;;
		 # -theme $HOME/.config/bspwm/rices/${RICETHEME}/scripts.rasi;;

  --rofisel)
    $HOME/.config/rofi/scripts/type-selector;;

  --rice)
	RiceSelector;;

  --terminal)
    alacritty;;

  --floating)
    alacritty --class FloaTerm,Alacritty \
					-o window.dimensions.lines=22 \
					window.dimensions.columns=90;;

  --update)
    alacritty --hold --class FloaTerm,Alacritty \
					-o window.dimensions.lines=22 \
					   window.dimensions.columns=90 \
					-e Updates --update-system;;

  --checkupdates)
	alacritty --hold --class Updating,Alacritty \
					-o window.dimensions.lines=22 \
					   window.dimensions.columns=47 \
					-e Updates --print-updates;;

  --ranger)
    alacritty --class FloaTerm,Alacritty \
					-o window.dimensions.lines=14 \
					   window.dimensions.columns=90 \
					-e ranger;;

  --nvim)
    alacritty -e nvim;;

  --music)
    alacritty --class FloaTerm,Alacritty \
					-o window.dimensions.lines=18 \
					   window.dimensions.columns=67 \
					-e ncmpcpp;;

  --fetch)
    alacritty --hold --class FloaTerm,Alacritty \
					-o window.dimensions.lines=26 \
					   window.dimensions.columns=40 \
					-e ~/.local/bin/sysfetch;;

  --openc)
    alacritty --class FloaTerm,Alacritty \
					-o window.dimensions.lines=26 \
					   window.dimensions.columns=90 \
					-e ~/.npm-packages/bin/openc;;

  --menu-zathura)
    alacritty --class FloaTerm,Alacritty \
					-o window.dimensions.lines=26 \
					   window.dimensions.columns=90 \
					-e ~/.npm-packages/bin/gmenu -y document -b Documents -o zathura;;

  --menu-config)
    alacritty --class FloaTerm,Alacritty \
					-o window.dimensions.lines=26 \
					   window.dimensions.columns=90 \
					-e ~/.npm-packages/bin/gmenu -y config -b .config -o nvim -t;;

  --menu-bin)
    alacritty --class FloaTerm,Alacritty \
					-o window.dimensions.lines=26 \
					   window.dimensions.columns=90 \
					-e ~/.npm-packages/bin/gmenu -y binary -b .local/bin -o nvim -t;;

  #Apps
  --filemanager)
	thunar;;

  --browser)
	brave-browser-nightly;;

  --editor)
	code;;

  --telegram)
	telegram;;

  --whats)
	whatsapp-nativefier --disable-gpu;;

  --soundcontrol)
    pavucontrol;;

  *)
    echo "Opción no válida";;
esac
