#!/usr/bin/env bash

read -r RICETHEME < "$HOME"/.config/bspwm/.rice
export RICETHEME
rice_dir="$HOME/.config/bspwm/rices/$RICETHEME"

case "$1" in
  --random)
    feh -z --no-fehbg --bg-fill $HOME/.local/share/backgrounds;;
    # feh -z --no-fehbg --bg-fill ${rice_dir}/walls;;
  --restore)
    $HOME/.fehbg;;
  *)
    echo "Option $1 not available";;
esac
